name: Evaluate LaunchDarkly flags
on: push
jobs:
  eval-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate flags
        id: ld
        uses: launchdarkly/gha-flags@v1.0.1
        with:
          sdk-key: ${{ secrets.LAUNCHDARKLY_SDK_KEY }}
          flags: developer-feature
      - name: If true
        if: fromJSON(steps.ld.outputs.developer-feature) == true
        run: echo "It's true"
      - name: If false
        if: fromJSON(steps.ld.outputs.developer-feature) == false
        run: echo "It's false"

