name: Manage Feature Flags with LaunchDarkly

on:
  push:
    branches:
      - master

jobs:
  manage-flags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Feature Flag
        uses: launchdarkly/ld-feature-flags-action@v1
        with:
          api-token: ${{ secrets.LD_ACCESS_TOKEN }}
          project-key: 'default'
          flag-key: 'developer-feature'
          environment: 'test'
          on: 'false'  # Set to 'false' to disable the flag
