name: Evaluate LaunchDarkly Flags

on:
  push:
    branches:
      - master

jobs:
  eval-flags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Evaluate feature flags
        id: ld
        uses: launchdarkly/gha-flags@v1.0.1
        with:
          sdk-key: ${{ secrets.LAUNCHDARKLY_SDK_KEY }}
          flags: developer-feature,false

      - name: If flag is true
        if: fromJSON(steps.ld.outputs.developer-feature) == true
        run: echo "Developer feature is enabled"

      - name: If flag is false
        if: fromJSON(steps.ld.outputs.developer-feature) == false
        run: echo "Developer feature is disabled"

