name: Evaluate LaunchDarkly flags
on: push
jobs:
  eval-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate flags
        id: flags
        uses: launchdarkly/gha-flags@v1.0.1
        with:
          sdk-key: ${{ secrets.LD_SDK_KEY }}
          flags: |
            show-textbox
            developer-feature
            tester-feature
      - name: Print flag values
        run: |
          echo ${{ steps.flags.outputs.show-textbox }}
          echo ${{ steps.flags.outputs.developer-feature }}
          echo ${{ steps.flags.outputs.tester-feature}}
